# Site
repository: HeeJaeMon123/HeeJaeMon123.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Heejae Park
title: M.S. Student at Seoultech
email: prkhj98@seoultech.ac.kr
#website: https://heejaemon123.tistory.com/

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  HeeJaeMon123
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: heejaemon1256
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0000-0002-6144-4831

# Additional icon links
additional_links:
- title: icelab.re.kr
  icon: fas fa-globe
  url: https://icelab.re.kr/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
gtag: "G-7S2WPKLRB0"
# google_analytics: G-7S2WPKLRB0

# About Section
# about_title: About Me My advisor is Prof. Laihyuk Park.
about_profile_image: images/san.jpg
about_content: | # this will include new lines to allow paragraphs
  I received the B.S. degree at the Seoul National University of Science and Technology, SEOULTECH in 2022 and I am currently pursuing M.S. degree at SEOULTECH.
  <br>
  <a href="https://heejaemon123.github.io/resume/" target="_blank"><i class='fa fa-file-pdf-o'></i> Curriculum Vitae (CV)</a>

content:
  - title: INTERESTS # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Next-generation Network (5G, 6G), Reconfigurable Intelligent Surface (RIS), Multicast, Machine Learning, and Deep Learning.
        # link: github.com/HeeJaeMon123
        # link_text: Project Website
        
        #additional_links:
         # - title:  Github page for project 
          #  icon: fab fa-github
           # url: https://github.com/HeeJaeMon123?tab=repositories  
 
  - title: Education # Title for the section
    layout: text # Type of content section (list/text)
    content: |
      - B.S., Feb. 2022, Computer Science and Engineering, Seoul National University of Science and Technology (Summa Cum Laude)


  - title: Teaching Assistant
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Introduction to Programming (1) at SEOULTECH (Spring 2022)
      - Probability and Random Variables at SEOULTECH (Spring 2022)

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
# - title: Projects # Title for the section
    #layout: list # Type of content section (list/text)
    #content:
     # - layout: top-middle
      #  title: Project Repository
       # link: github.com/HeeJaeMon123
        # link_text: Project Website
        
        #additional_links:
         # - title:  Github page for project 
          #  icon: fab fa-github
           # url: https://github.com/HeeJaeMon123?tab=repositories 
            
     #   quote: >
      #    This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
       # description: | # this will include new lines to allow paragraphs
        #  I started this project as a way if learning <mark>React</mark>
